"""
This migration adds a few locations to the database to get the ball rolling.

You can add, edit and delete Locations using Django's built in admin site.
"""
# Generated by Django 4.1.2 on 2022-10-25 11:05
from decimal import Decimal as D

from django.db import migrations


def add_locations(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Location = apps.get_model("forecast", "Location")
    db_alias = schema_editor.connection.alias
    Location.objects.using(db_alias).bulk_create(
        [
            Location(name="Bergen", latitude=D("60.3929"), longitude=D("5.3241")),
            Location(name="Oslo", latitude=D("59.9115"), longitude=D("10.7579")),
            Location(name="Tromsø", latitude=D("69.6489"), longitude=D("18.9551")),
            Location(name="Kristiansand", latitude=D("58.1472"), longitude=D("7.9972")),
        ]
    )


def remove_locations(apps, schema_editor):
    # add_locations() creates four Location instances,
    # so remove_locations() should delete them.
    Location = apps.get_model("forecast", "Location")
    db_alias = schema_editor.connection.alias
    Location.objects.using(db_alias).filter(
        name__in=["Bergen", "Oslo", "Tromsø", "Kristiansand"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_locations, remove_locations),
    ]
